version: "3.9"

networks:
  shared-network:
    external: true

services:
  # -----------------------------
  # RabbitMQ
  # -----------------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMQ__Username}
      RABBITMQ_DEFAULT_PASS: ${RabbitMQ__Password}
    networks:
      - shared-network

  # -----------------------------
  # Redis
  # -----------------------------
  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${Redis__Password}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${Redis__Password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

  # -----------------------------
  # Workers
  # -----------------------------
  steam-worker:
    build:
      context: ./workers
      dockerfile: Dockerfile.dev
    container_name: steam-worker
    env_file:
      - ./.env
    environment:
      - NODE_ENV=docker
    volumes:
      - ./workers/dist:/app/dist
      - ./workers/package.json:/app/package.json
      - ./workers/node_modules:/app/node_modules
    working_dir: /app
    command: ["npm", "run", "steam:watch"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    # restart: unless-stopped #For some reason fails at first start, loads on second
    networks:
      - shared-network
  
  instantgaming-worker:
    build:
      context: ./workers
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=docker
    volumes:
      - ./workers:/app:cached
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "instantgaming:watch"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    # restart: unless-stopped #For some reason fails at first start, loads on second
    networks:
      - shared-network
    deploy:
      replicas: 5

  # -----------------------------
  # Backend / API
  # -----------------------------
  gamesfinder-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - shared-network
