networks:
  shared-network:
    external: true

services:
  # -----------------------------
  # RabbitMQ
  # -----------------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMQ__Username}
      RABBITMQ_DEFAULT_PASS: ${RabbitMQ__Password}
    networks:
      - shared-network

  # -----------------------------
  # Redis
  # -----------------------------
  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${Redis__Password}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${Redis__Password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

  # -----------------------------
  # Workers
  # -----------------------------
  steam-worker:
    build:
      context: ./workers
      dockerfile: Dockerfile.prod
    container_name: steam-worker
    env_file:
      - ./.env
    environment:
      - NODE_ENV=docker
    command: ["npm", "run", "steam"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    # restart: unless-stopped #For some reason fails at first start, loads on second
    networks:
      - shared-network
  
  instantgaming-worker:
    build:
      context: ./workers
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env
    environment:
      - NODE_ENV=docker
    command: ["npm", "run", "instantgaming"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    # restart: unless-stopped #For some reason fails at first start, loads on second
    networks:
      - shared-network
    deploy:
      replicas: 5

  # -----------------------------
  # Backend / API
  # -----------------------------
  gamesfinder-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - ./.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - shared-network
